on:
  push:
    branches:
      - main
    paths:
      - 'APIProject/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Install dependencies
        working-directory: APIProject/LambdaFunctions/UserDetails-LF
        run: npm install
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: falnyr/aws-sam-deploy-action@v1.3.0
      env:
        TEMPLATE: 'APIProject/template.json'
        AWS_STACK_NAME: SWGoH-API
        AWS_REGION: 'us-west-2'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_BUCKET_PREFIX: 'SWGoH-API'
        AWS_DEPLOY_BUCKET: 'honersports.com'
