on:
  push:
    branches:
      - main
    paths:
      - 'APIProject/**'
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-west-2'
      # sam build 
      - working-directory: APIProject
        run: sam build --use-container
      - working-directory: APIProject
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name SWGoH-API --s3-bucket honersports.com --s3-prefix SWGoH-API --capabilities CAPABILITY_IAM --region us-west-2
